import Head from "next/head";
import Image from "next/image";
import styles from "@/src/styles/Home.module.css";
import { Layout } from "@/src/component/layout";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>hoge</div>
        <Link href="/new">Newへ</Link>
      </Layout>
    </div>
  );
}
