import firebase from "firebase/compat/app";
import "firebase/compat/auth";
import "firebase/compat/firestore";
import "../hooks/firebase/fire";
import Head from "next/head";

import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import { Form } from "src/component/form/form";
import { useState, useEffect } from "react";
/**
 * @deprecated
 * ログイン画面はpopでだすので、ログイン画面は不要
 * @returns
 */
export default function Login() {
  const auth = firebase.auth();
  const provider = new firebase.auth.GoogleAuthProvider();

  const [message, setMessage] = useState("wait...");

  // ログインのポップ出す処理
  // useEffect(() => {
  //   auth.signInWithPopup(provider).then((result: any) => {
  //     console.log(auth);
  //     setMessage("logined: " + result?.user.displayName);
  //   });
  // }, []);
  {
    /* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */
  }
  <h1>Login</h1>;

  return (
    <div>
      <div className="alert alert-primary text-center">
        <h5 className="mb-4">{message}</h5>
        <p className="h6 text-left">
          uid: {auth.currentUser != null ? auth.currentUser.uid : ""}
          <br />
          displayName:{" "}
          {auth.currentUser != null ? auth.currentUser.displayName : ""}
          <br />
          email: {auth.currentUser != null ? auth.currentUser.email : ""}
          <br />
          phoneNumber:{" "}
          {auth.currentUser != null ? auth.currentUser.phoneNumber : ""}
        </p>
      </div>
    </div>
  );
}
