import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Form } from "src/component/form/form";
import { Button } from "@nextui-org/react";

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Login</div>
      <Button>Click me</Button>;
      <Form />
    </div>
  );
}
