import Head from "next/head";
import styles from "../styles/Home.module.css";
import { KaiganForm } from "@/src/component/form/kaiganForm";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import React from "react";
import { useRouter } from "next/router";
import { Kaigan } from "../interface/kaigan";

export default function New() {
  const router = useRouter();
  console.log(router.query);
  const updateKaigan: Kaigan = {
    date: typeof router.query.date === "string" ? router.query.date : "",
    rank: Number(router.query.rank),
    places:
      typeof router.query.places !== "string"
        ? router.query.places
        : [router.query.places],
    clubs:
      typeof router.query.clubs !== "string"
        ? router.query.clubs
        : [router.query.clubs],
    actions:
      typeof router.query.actions !== "string"
        ? router.query.actions
        : [router.query.actions],
    bodyParts:
      typeof router.query.bodyParts !== "string"
        ? router.query.bodyParts
        : [router.query.bodyParts],
    errors:
      typeof router.query.errors !== "string"
        ? router.query.errors
        : [router.query.errors],
    detail: typeof router.query.detail === "string" ? router.query.detail : "",
  };
  console.log(updateKaigan);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <KaiganForm
        //  kgn={updateKaigan}
        date={updateKaigan.date}
        rank={updateKaigan.rank}
        places={updateKaigan.places}
        clubs={updateKaigan.clubs}
        actions={updateKaigan.actions}
        bodyParts={updateKaigan.bodyParts}
        errors={updateKaigan.errors}
        detail={updateKaigan.detail}
      />
    </div>
  );
}
