import Head from "next/head";
import styles from "../styles/Home.module.css";
import { KaiganForm } from "@/src/component/form/kaiganForm";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import React from "react";
import { useRouter } from "next/router";

export default function New() {
  const router = useRouter();
  console.log(router.query);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <KaiganForm kgn={router.query} /> */}
    </div>
  );
}
